window.ODR_DATA = {
  "generated": "2026-09-07",
  "period": {
    "start": "2026-06-15",
    "end": "2026-08-31",
    "label_ua": "15 черв — 31 серп 2026 (12 повних тижнів)",
    "label_en": "15 Jun — 31 Aug 2026 (12 completed weeks)",
    "footer_ua": "дані станом на 6 вересня 2026 (12 повних тижнів)",
    "footer_en": "data as of 6 September 2026 (12 completed weeks)",
    "last_week_ua": "31 серп",
    "last_week_en": "31 Aug"
  },
  "kpis": {
    "odr_avg": 19.1,
    "odr_last": 21.0,
    "repl": 21.0,
    "qty_share": 65.0,
    "last_is_peak": false
  },
  "weeks_ua": [
    "15 черв",
    "22 черв",
    "29 черв",
    "6 лип",
    "13 лип",
    "20 лип",
    "27 лип",
    "3 серп",
    "10 серп",
    "17 серп",
    "24 серп",
    "31 серп"
  ],
  "weeks_en": [
    "15 Jun",
    "22 Jun",
    "29 Jun",
    "6 Jul",
    "13 Jul",
    "20 Jul",
    "27 Jul",
    "3 Aug",
    "10 Aug",
    "17 Aug",
    "24 Aug",
    "31 Aug"
  ],
  "defect_types": {
    "qty": [
      1618,
      1723,
      2253,
      2623,
      2291,
      2566,
      2811,
      3464,
      4984,
      4270,
      4373,
      4542
    ],
    "weight": [
      614,
      625,
      823,
      876,
      863,
      914,
      927,
      1168,
      2844,
      1286,
      1256,
      1386
    ],
    "price": [
      348,
      337,
      326,
      251,
      149,
      128,
      134,
      197,
      3721,
      362,
      263,
      436
    ]
  },
  "shares": {
    "qty": 65.0,
    "weight": 23.5,
    "price": 11.5
  },
  "order_level": {
    "qty": 20.2,
    "qty_avg": 17.9,
    "weight": 2.1,
    "price": 0.0,
    "ua_qty": 18.2,
    "ua_wt": 2.1,
    "ua_price": 0,
    "varus_qty": 53.1,
    "kop_qty": 29.2,
    "worst_wt_brand": "RODYNNA KOVBASKA",
    "worst_wt": 4.7,
    "ro_price": 16.3
  },
  "market": {
    "odr": [
      13.7,
      14.5,
      16.7,
      18.8,
      16.8,
      18.5,
      18.9,
      19.6,
      22.7,
      22.5,
      21.9,
      21.0
    ],
    "repl": [
      18.3,
      20.0,
      21.6,
      23.7,
      22.0,
      25.7,
      21.0,
      19.0,
      21.5,
      21.6,
      20.1,
      18.5
    ],
    "orders": [
      8473,
      8428,
      9055,
      8796,
      8945,
      8763,
      9187,
      10448,
      12535,
      10884,
      10791,
      10907
    ]
  },
  "brand_odr": {
    "VARUS": [
      38.0,
      46.1,
      50.6,
      55.3,
      52.7,
      51.9,
      54.2,
      55.4,
      55.6,
      58.9,
      61.3,
      63.8
    ],
    "KOPIYKA": [
      41.3,
      30.9,
      39.1,
      36.2,
      36.0,
      33.9,
      32.9,
      29.6,
      41.6,
      36.2,
      26.2,
      25.3
    ],
    "SANTIM": [
      38.1,
      34.9,
      44.0,
      26.2,
      29.6,
      32.8,
      24.5,
      38.2,
      39.2,
      28.3,
      34.5,
      29.3
    ],
    "RUKAVYCHKA": [
      22.4,
      25.5,
      28.0,
      30.9,
      25.5,
      25.5,
      29.0,
      22.2,
      20.4,
      21.4,
      20.0,
      29.7
    ],
    "TAISTRA": [
      22.9,
      24.3,
      30.2,
      20.1,
      21.6,
      20.8,
      25.3,
      16.9,
      16.6,
      20.7,
      13.0,
      17.3
    ],
    "KOPIYKA MINI": [
      18.9,
      22.0,
      21.1,
      20.2,
      14.8,
      28.0,
      15.3,
      19.5,
      29.1,
      32.4,
      19.0,
      11.1
    ],
    "CAFE RYNOK": [
      11.9,
      13.9,
      17.8,
      13.8,
      13.3,
      8.2,
      13.7,
      13.1,
      13.9,
      15.0,
      10.7,
      13.0
    ],
    "LOKO": [
      3.7,
      6.3,
      7.2,
      6.3,
      8.3,
      6.3,
      6.1,
      8.0,
      6.6,
      5.2,
      5.5,
      6.9
    ],
    "HOP HEY": [
      4.7,
      5.7,
      6.4,
      6.5,
      3.7,
      6.3,
      4.6,
      6.2,
      4.4,
      4.8,
      4.4,
      4.2
    ]
  },
  "partners": [
    {
      "b": "VARUS",
      "items": 210866,
      "avg": 54.7,
      "last": 63.8,
      "d": 25.8,
      "qty": 14.8,
      "repl": 15.7,
      "wt": 0.9,
      "orepl": 70.7,
      "st": "crit",
      "problem_ua": "Визначає ринковий ODR: найбільший grocery-обсяг, середній ODR 54.7%, останній тиждень 63.8% (+25.8 п.п. за 12 тижнів). Quantity 14.8% + order replacement 70.7%.",
      "action_ua": "1) Прибрати пакети з quantity defect. 2) Deep-dive найгірших магазинів. 3) Daily OOS sync по напоях. 4) Ціль ODR <35% за 8 тижнів.",
      "problem_en": "Sets market ODR: largest grocery volume, average ODR 54.7%, latest week 63.8% (+25.8 pp over 12 weeks). Quantity 14.8% plus order replacement 70.7%.",
      "action_en": "1) Remove bags from quantity defect. 2) Deep-dive the worst stores. 3) Daily OOS sync on beverages. 4) Target ODR <35% within 8 weeks."
    },
    {
      "b": "LOKO",
      "items": 77158,
      "avg": 6.5,
      "last": 6.9,
      "d": 3.2,
      "qty": 1.0,
      "repl": 0,
      "wt": 0.3,
      "orepl": 0,
      "st": "good",
      "problem_ua": "Найкращий великий партнер: середній ODR 6.5%, замін немає. Останній тиждень 6.9% (+3.2 п.п.).",
      "action_ua": "Зафіксувати процеси наявності як playbook для grocery. Тримати ODR <7%.",
      "problem_en": "Best large partner: average ODR 6.5%, no replacements. Latest week 6.9% (+3.2 pp).",
      "action_en": "Document availability processes as a grocery playbook. Keep ODR below 7%."
    },
    {
      "b": "HOP HEY",
      "items": 33498,
      "avg": 5.1,
      "last": 4.2,
      "d": -0.5,
      "qty": 1.3,
      "repl": 1.7,
      "wt": 0.3,
      "orepl": 3.8,
      "st": "good",
      "problem_ua": "ODR низький і стабільний (сер. 5.1%, ост. 4.2%), але order replacement 3.8%.",
      "action_ua": "Не чіпати ODR. Перевірити каталог і правила замін.",
      "problem_en": "ODR is low and stable (avg 5.1%, last 4.2%), but order replacement is 3.8%.",
      "action_en": "Leave ODR alone. Review the catalog and substitution rules."
    },
    {
      "b": "KOPIYKA",
      "items": 27297,
      "avg": 33.8,
      "last": 25.3,
      "d": -16.0,
      "qty": 7.5,
      "repl": 5.6,
      "wt": 1.1,
      "orepl": 25.0,
      "st": "crit",
      "problem_ua": "Високий grocery ODR: сер. 33.8%, останній тиждень 25.3% (-16.0 п.п.). Quantity 7.5%, order replacement 25.0%.",
      "action_ua": "Weekly ops review з AM. Root-cause по OOS у напоях і снеках. Ціль <28%.",
      "problem_en": "High grocery ODR: avg 33.8%, latest week 25.3% (-16.0 pp). Quantity 7.5%, order replacement 25.0%.",
      "action_en": "Weekly ops review with the AM. Root-cause OOS in beverages and snacks. Target <28%."
    },
    {
      "b": "TAISTRA",
      "items": 13754,
      "avg": 20.9,
      "last": 17.3,
      "d": -5.6,
      "qty": 4.5,
      "repl": 1.2,
      "wt": 0.1,
      "orepl": 6.8,
      "st": "high",
      "problem_ua": "Прогрес -5.6 п.п. (перший тиждень → 17.3%). Quantity 4.5%.",
      "action_ua": "Закріпити прогрес і розібрати кейс як приклад для grocery.",
      "problem_en": "Improvement -5.6 pp (first week → 17.3%). Quantity 4.5%.",
      "action_en": "Lock in the progress and use the case as a grocery reference."
    },
    {
      "b": "CAFE RYNOK",
      "items": 20298,
      "avg": 13.3,
      "last": 13.0,
      "d": 1.1,
      "qty": 3.2,
      "repl": 2.2,
      "wt": 0,
      "orepl": 9.7,
      "st": "watch",
      "problem_ua": "Помірний ODR (сер. 13.3%, ост. 13.0%). Item replacement 2.2%, order replacement 9.7%.",
      "action_ua": "Catalog audit: чи replacement реальний, чи артефакт меню.",
      "problem_en": "Moderate ODR (avg 13.3%, last 13.0%). Item replacement 2.2%, order replacement 9.7%.",
      "action_en": "Catalog audit: confirm whether replacements are real or a menu artefact."
    },
    {
      "b": "RUKAVYCHKA",
      "items": 10602,
      "avg": 24.8,
      "last": 29.7,
      "d": 7.3,
      "qty": 5.3,
      "repl": 1.0,
      "wt": 0.7,
      "orepl": 4.8,
      "st": "high",
      "problem_ua": "ODR сер. 24.8%, останній тиждень 29.7% (+7.3 п.п.). Quantity 5.3%.",
      "action_ua": "Продовжити дисципліну наявності. Порівняти процеси з TAISTRA.",
      "problem_en": "ODR avg 24.8%, latest week 29.7% (+7.3 pp). Quantity 5.3%.",
      "action_en": "Keep availability discipline. Compare processes with TAISTRA."
    },
    {
      "b": "SANTIM",
      "items": 6590,
      "avg": 33.3,
      "last": 29.3,
      "d": -8.8,
      "qty": 6.7,
      "repl": 4.0,
      "wt": 1.1,
      "orepl": 19.2,
      "st": "crit",
      "problem_ua": "Високий ODR: сер. 33.3%, останній тиждень 29.3% (-8.8 п.п.). Quantity 6.7%, weight 1.1%.",
      "action_ua": "Спільний review з KOPIYKA. Точність вагових позицій плюс OOS-контроль.",
      "problem_en": "High ODR: avg 33.3%, latest week 29.3% (-8.8 pp). Quantity 6.7%, weight 1.1%.",
      "action_en": "Joint review with KOPIYKA. Weighted-item accuracy plus OOS control."
    },
    {
      "b": "KOPIYKA MINI",
      "items": 6184,
      "avg": 21.5,
      "last": 11.1,
      "d": -7.8,
      "qty": 5.4,
      "repl": 3.7,
      "wt": 0.3,
      "orepl": 15.3,
      "st": "high",
      "problem_ua": "Волатильний mini-формат: сер. 21.5%, останній тиждень 11.1% (-7.8 п.п.).",
      "action_ua": "Стабілізувати наявність у mini-форматі, не дати підтягнутись до KOPIYKA.",
      "problem_en": "Volatile mini format: avg 21.5%, latest week 11.1% (-7.8 pp).",
      "action_en": "Stabilise mini-format availability; do not let it drift to KOPIYKA's level."
    },
    {
      "b": "RODYNNA KOVBASKA",
      "items": 978,
      "avg": 52.7,
      "last": 40.5,
      "d": 6.1,
      "qty": 21.7,
      "repl": 4.1,
      "wt": 4.7,
      "orepl": 12.5,
      "st": "crit",
      "problem_ua": "Найгірші item-метрики: quantity 21.7%, weight 4.7%, ODR сер. 52.7%.",
      "action_ua": "Пріоритет — вагові SKU. Не масштабувати, доки ODR >30%.",
      "problem_en": "Worst item-level metrics: quantity 21.7%, weight 4.7%, ODR avg 52.7%.",
      "action_en": "Priority is weighted SKUs. Do not scale while ODR stays above 30%."
    },
    {
      "b": "ANRI-PHARM",
      "items": 3108,
      "avg": 4.1,
      "last": 0.6,
      "d": -9.2,
      "qty": 2.5,
      "repl": 0,
      "wt": 0,
      "orepl": 0,
      "st": "good",
      "problem_ua": "Аптечний формат: ODR сер. 4.1%, останній тиждень 0.6%.",
      "action_ua": "Тримати поточний рівень, окремих дій не потрібно.",
      "problem_en": "Pharmacy format: ODR avg 4.1%, latest week 0.6%.",
      "action_en": "Hold the current level; no dedicated actions needed."
    },
    {
      "b": "BRSM",
      "items": 1554,
      "avg": 6.6,
      "last": 5.9,
      "d": 5.9,
      "qty": 2.6,
      "repl": 0.7,
      "wt": 0,
      "orepl": 1.6,
      "st": "good",
      "problem_ua": "Малий обсяг, ODR сер. 6.6%, останній тиждень 5.9% (+5.9 п.п.).",
      "action_ua": "Моніторинг. Якщо ODR стабільно >10% — перевірка наявності на АЗС-форматі.",
      "problem_en": "Small volume, ODR avg 6.6%, latest week 5.9% (+5.9 pp).",
      "action_en": "Monitor. If ODR stays above 10%, run an availability check on the fuel-station format."
    },
    {
      "b": "NO TABOO",
      "items": 647,
      "avg": 7.3,
      "last": 3.6,
      "d": -1.2,
      "qty": 4.8,
      "repl": 0.8,
      "wt": 0,
      "orepl": 1.5,
      "st": "good",
      "problem_ua": "Малий обсяг. ODR сер. 7.3%, останній тиждень 3.6% (-1.2 п.п.).",
      "action_ua": "Низький пріоритет, підтримувати рівень.",
      "problem_en": "Small volume. ODR avg 7.3%, latest week 3.6% (-1.2 pp).",
      "action_en": "Low priority; maintain the current level."
    }
  ],
  "dbx15": [
    [
      "VARUS",
      31124,
      54.7,
      53.1,
      5.4,
      0,
      70.7
    ],
    [
      "LOKO",
      13583,
      6.5,
      5.0,
      1.6,
      0,
      0
    ],
    [
      "HOP HEY",
      10108,
      5.1,
      4.1,
      1.0,
      0,
      3.8
    ],
    [
      "BEER MARKET",
      7093,
      0,
      0,
      0,
      0,
      0
    ],
    [
      "KOPIYKA",
      6887,
      31.6,
      29.2,
      4.8,
      0,
      22.3
    ],
    [
      "CAFE RYNOK",
      4265,
      13.3,
      13.3,
      0,
      0,
      9.7
    ],
    [
      "PYVNA BORODA",
      3685,
      0,
      0,
      0,
      0,
      0
    ],
    [
      "BEERLAND K",
      3316,
      0,
      0,
      0,
      0,
      0
    ],
    [
      "LEPRUKON",
      2985,
      0,
      0,
      0,
      0,
      0
    ],
    [
      "REMESLO BREWERY",
      2909,
      0,
      0,
      0,
      0,
      0
    ],
    [
      "TAISTRA",
      2262,
      20.9,
      20.3,
      0.8,
      0,
      6.8
    ],
    [
      "RUKAVYCHKA",
      1912,
      24.8,
      22.6,
      3.3,
      0,
      4.8
    ],
    [
      "OKKO CAFE GROUP",
      1689,
      0,
      0,
      0,
      0,
      0
    ],
    [
      "ANRI-PHARM",
      1675,
      4.1,
      4.1,
      0,
      0,
      0
    ],
    [
      "TOCHKA",
      1608,
      0,
      0,
      0,
      0,
      0
    ]
  ],
  "stores": [
    [
      "м. Київ (Софіївська Борщагівка), вул. Лесі Українки 30",
      721,
      31.3,
      21.6
    ],
    [
      "м. Київ, вул. Маршала Малиновського, 12А",
      4055,
      21.9,
      19.5
    ],
    [
      "м. Київ, ул.Васильковская,34",
      7653,
      19.4,
      20.6
    ],
    [
      "VARUS, Проспект Червоної Калини 44A",
      4921,
      18.7,
      19.4
    ],
    [
      "м. Дніпро, ул.Паникахи, 15",
      2784,
      15.2,
      22.3
    ],
    [
      "Vasylia Tiutiunnyka St, 39А, Kyiv, 02000",
      6487,
      20.1,
      17.2
    ],
    [
      "м. Одеса, вул.Французький бульвар, 22",
      1567,
      23.0,
      13.9
    ],
    [
      "м. Дніпро, бул.Европейский, 1д",
      3919,
      18.2,
      18.6
    ]
  ],
  "cats": [
    [
      "Grocery Food",
      173459,
      6.9,
      12.0,
      32823
    ],
    [
      "Various, mixed",
      125426,
      10.4,
      5.0,
      19410
    ],
    [
      "Non-Food",
      18759,
      4.8,
      17.6,
      4200
    ],
    [
      "Shashlik",
      14473,
      15.9,
      7.7,
      3423
    ],
    [
      "Cola",
      11670,
      13.2,
      6.9,
      2341
    ],
    [
      "Still water",
      14633,
      10.3,
      5.2,
      2258
    ],
    [
      "Chips & Crackers",
      11246,
      10.7,
      5.2,
      1778
    ],
    [
      "Snacks",
      23802,
      2.7,
      1.5,
      988
    ],
    [
      "Wheat Beer",
      21543,
      1.6,
      0.9,
      545
    ],
    [
      "Vodka",
      5246,
      6.3,
      3.9,
      535
    ]
  ],
  "partner_drill": {
    "partners": [
      {
        "name": "VARUS",
        "orders": 31124,
        "defect_orders": 17031,
        "odr": 54.7,
        "repl_orders": 22004,
        "repl": 70.7,
        "qty_orders": 16527,
        "qty": 53.1
      },
      {
        "name": "KOPIYKA",
        "orders": 4574,
        "defect_orders": 1548,
        "odr": 33.8,
        "repl_orders": 1142,
        "repl": 25.0,
        "qty_orders": 1427,
        "qty": 31.2
      },
      {
        "name": "CAFE RYNOK",
        "orders": 4265,
        "defect_orders": 568,
        "odr": 13.3,
        "repl_orders": 412,
        "repl": 9.7,
        "qty_orders": 568,
        "qty": 13.3
      },
      {
        "name": "RUKAVYCHKA",
        "orders": 1912,
        "defect_orders": 475,
        "odr": 24.8,
        "repl_orders": 92,
        "repl": 4.8,
        "qty_orders": 433,
        "qty": 22.6
      },
      {
        "name": "TAISTRA",
        "orders": 2262,
        "defect_orders": 472,
        "odr": 20.9,
        "repl_orders": 153,
        "repl": 6.8,
        "qty_orders": 460,
        "qty": 20.3
      },
      {
        "name": "SANTIM",
        "orders": 1094,
        "defect_orders": 364,
        "odr": 33.3,
        "repl_orders": 210,
        "repl": 19.2,
        "qty_orders": 333,
        "qty": 30.4
      },
      {
        "name": "KOPIYKA MINI",
        "orders": 1219,
        "defect_orders": 262,
        "odr": 21.5,
        "repl_orders": 186,
        "repl": 15.3,
        "qty_orders": 252,
        "qty": 20.7
      },
      {
        "name": "RODYNNA KOVBASKA",
        "orders": 256,
        "defect_orders": 135,
        "odr": 52.7,
        "repl_orders": 32,
        "repl": 12.5,
        "qty_orders": 109,
        "qty": 42.6
      }
    ],
    "categories": {
      "VARUS": [
        {
          "category": "Various, mixed",
          "orders": 26092,
          "items": 58893,
          "affected_orders": 8621,
          "contribution": 27.7,
          "qty": 18.8,
          "repl": 9.2,
          "weight": 1.1,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "orders": 29903,
          "items": 96116,
          "affected_orders": 7603,
          "contribution": 24.4,
          "qty": 10.4,
          "repl": 20.8,
          "weight": 0.9,
          "price": 0
        },
        {
          "category": "Shashlik",
          "orders": 7251,
          "items": 7186,
          "affected_orders": 1774,
          "contribution": 5.7,
          "qty": 25.7,
          "repl": 11.6,
          "weight": 2.4,
          "price": 0
        },
        {
          "category": "Cola",
          "orders": 6040,
          "items": 5537,
          "affected_orders": 1366,
          "contribution": 4.4,
          "qty": 25.8,
          "repl": 13.7,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "orders": 7728,
          "items": 8227,
          "affected_orders": 1286,
          "contribution": 4.1,
          "qty": 16.6,
          "repl": 8.6,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Chips & Crackers",
          "orders": 3993,
          "items": 4503,
          "affected_orders": 933,
          "contribution": 3.0,
          "qty": 23.4,
          "repl": 11.4,
          "weight": 0.4,
          "price": 0
        },
        {
          "category": "Non-Food",
          "orders": 8738,
          "items": 9365,
          "affected_orders": 653,
          "contribution": 2.1,
          "qty": 7.2,
          "repl": 30.7,
          "weight": 0.1,
          "price": 0
        },
        {
          "category": "Snacks",
          "orders": 3191,
          "items": 2935,
          "affected_orders": 428,
          "contribution": 1.4,
          "qty": 13.6,
          "repl": 6.1,
          "weight": 1.6,
          "price": 0
        },
        {
          "category": "Vodka",
          "orders": 2593,
          "items": 2562,
          "affected_orders": 281,
          "contribution": 0.9,
          "qty": 11.0,
          "repl": 7.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Orange",
          "orders": 1435,
          "items": 1238,
          "affected_orders": 233,
          "contribution": 0.7,
          "qty": 19.1,
          "repl": 10.1,
          "weight": 0.1,
          "price": 0
        }
      ],
      "KOPIYKA": [
        {
          "category": "Grocery Food",
          "orders": 3714,
          "items": 9946,
          "affected_orders": 708,
          "contribution": 15.5,
          "qty": 7.6,
          "repl": 5.4,
          "weight": 1.7,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "orders": 3436,
          "items": 6609,
          "affected_orders": 646,
          "contribution": 14.1,
          "qty": 10.3,
          "repl": 4.7,
          "weight": 1.0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "orders": 1794,
          "items": 2126,
          "affected_orders": 163,
          "contribution": 3.6,
          "qty": 6.4,
          "repl": 7.1,
          "weight": 1.7,
          "price": 0
        },
        {
          "category": "Snacks",
          "orders": 466,
          "items": 455,
          "affected_orders": 69,
          "contribution": 1.5,
          "qty": 13.2,
          "repl": 6.6,
          "weight": 2.0,
          "price": 0
        },
        {
          "category": "Chips & Crackers",
          "orders": 585,
          "items": 727,
          "affected_orders": 51,
          "contribution": 1.1,
          "qty": 7.4,
          "repl": 4.4,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "orders": 2104,
          "items": 2691,
          "affected_orders": 47,
          "contribution": 1.0,
          "qty": 1.8,
          "repl": 11.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "orders": 924,
          "items": 1024,
          "affected_orders": 43,
          "contribution": 0.9,
          "qty": 4.3,
          "repl": 1.6,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Cola",
          "orders": 880,
          "items": 879,
          "affected_orders": 39,
          "contribution": 0.9,
          "qty": 4.3,
          "repl": 1.6,
          "weight": 0.1,
          "price": 0
        },
        {
          "category": "Vodka",
          "orders": 488,
          "items": 482,
          "affected_orders": 26,
          "contribution": 0.6,
          "qty": 5.6,
          "repl": 2.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Honey Cake",
          "orders": 173,
          "items": 162,
          "affected_orders": 22,
          "contribution": 0.5,
          "qty": 13.0,
          "repl": 3.7,
          "weight": 0.6,
          "price": 0
        }
      ],
      "CAFE RYNOK": [
        {
          "category": "Various, mixed",
          "orders": 3481,
          "items": 6995,
          "affected_orders": 292,
          "contribution": 6.8,
          "qty": 4.5,
          "repl": 3.0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "orders": 1480,
          "items": 1601,
          "affected_orders": 104,
          "contribution": 2.4,
          "qty": 6.7,
          "repl": 5.4,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "orders": 4265,
          "items": 6723,
          "affected_orders": 85,
          "contribution": 2.0,
          "qty": 1.3,
          "repl": 0.7,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Cola",
          "orders": 384,
          "items": 389,
          "affected_orders": 18,
          "contribution": 0.4,
          "qty": 4.6,
          "repl": 3.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Nigiri",
          "orders": 271,
          "items": 286,
          "affected_orders": 15,
          "contribution": 0.4,
          "qty": 5.6,
          "repl": 4.9,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Sandwich",
          "orders": 1119,
          "items": 1289,
          "affected_orders": 14,
          "contribution": 0.3,
          "qty": 1.1,
          "repl": 1.0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Carbonara",
          "orders": 124,
          "items": 96,
          "affected_orders": 8,
          "contribution": 0.2,
          "qty": 8.3,
          "repl": 6.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Caesar Salad",
          "orders": 157,
          "items": 130,
          "affected_orders": 8,
          "contribution": 0.2,
          "qty": 6.2,
          "repl": 3.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Croissant",
          "orders": 187,
          "items": 156,
          "affected_orders": 7,
          "contribution": 0.2,
          "qty": 4.5,
          "repl": 3.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Napoleon Cake",
          "orders": 90,
          "items": 73,
          "affected_orders": 7,
          "contribution": 0.2,
          "qty": 9.6,
          "repl": 4.1,
          "weight": 0,
          "price": 0
        }
      ],
      "RUKAVYCHKA": [
        {
          "category": "Grocery Food",
          "orders": 1380,
          "items": 4351,
          "affected_orders": 248,
          "contribution": 13.0,
          "qty": 5.4,
          "repl": 1.0,
          "weight": 1.3,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "orders": 1203,
          "items": 2540,
          "affected_orders": 125,
          "contribution": 6.5,
          "qty": 5.0,
          "repl": 1.2,
          "weight": 0.4,
          "price": 0
        },
        {
          "category": "Non-Food",
          "orders": 566,
          "items": 595,
          "affected_orders": 42,
          "contribution": 2.2,
          "qty": 7.2,
          "repl": 1.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "orders": 209,
          "items": 194,
          "affected_orders": 39,
          "contribution": 2.0,
          "qty": 18.0,
          "repl": 2.1,
          "weight": 3.1,
          "price": 0
        },
        {
          "category": "Still water",
          "orders": 258,
          "items": 253,
          "affected_orders": 12,
          "contribution": 0.6,
          "qty": 4.7,
          "repl": 1.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Chips & Crackers",
          "orders": 259,
          "items": 317,
          "affected_orders": 12,
          "contribution": 0.6,
          "qty": 3.8,
          "repl": 0.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Sparkling Water",
          "orders": 294,
          "items": 308,
          "affected_orders": 11,
          "contribution": 0.6,
          "qty": 3.9,
          "repl": 0.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Wheat Beer",
          "orders": 200,
          "items": 193,
          "affected_orders": 9,
          "contribution": 0.5,
          "qty": 4.7,
          "repl": 1.0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Napoleon Cake",
          "orders": 14,
          "items": 9,
          "affected_orders": 7,
          "contribution": 0.4,
          "qty": 55.6,
          "repl": 0,
          "weight": 22.2,
          "price": 0
        },
        {
          "category": "Cola",
          "orders": 353,
          "items": 361,
          "affected_orders": 6,
          "contribution": 0.3,
          "qty": 1.7,
          "repl": 0.3,
          "weight": 0,
          "price": 0
        }
      ],
      "TAISTRA": [
        {
          "category": "Grocery Food",
          "orders": 1706,
          "items": 4278,
          "affected_orders": 191,
          "contribution": 8.4,
          "qty": 5.3,
          "repl": 1.1,
          "weight": 0.2,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "orders": 1653,
          "items": 3233,
          "affected_orders": 184,
          "contribution": 8.1,
          "qty": 6.3,
          "repl": 2.4,
          "weight": 0.1,
          "price": 0
        },
        {
          "category": "Shashlik",
          "orders": 505,
          "items": 558,
          "affected_orders": 37,
          "contribution": 1.6,
          "qty": 7.0,
          "repl": 0.7,
          "weight": 0.7,
          "price": 0
        },
        {
          "category": "Still water",
          "orders": 605,
          "items": 688,
          "affected_orders": 24,
          "contribution": 1.1,
          "qty": 3.5,
          "repl": 1.6,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "orders": 1935,
          "items": 2296,
          "affected_orders": 23,
          "contribution": 1.0,
          "qty": 1.0,
          "repl": 0.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Wheat Beer",
          "orders": 250,
          "items": 260,
          "affected_orders": 15,
          "contribution": 0.7,
          "qty": 5.8,
          "repl": 0.4,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Vodka",
          "orders": 273,
          "items": 276,
          "affected_orders": 12,
          "contribution": 0.5,
          "qty": 4.3,
          "repl": 1.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Snacks",
          "orders": 199,
          "items": 188,
          "affected_orders": 12,
          "contribution": 0.5,
          "qty": 6.4,
          "repl": 1.6,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Chips & Crackers",
          "orders": 318,
          "items": 375,
          "affected_orders": 9,
          "contribution": 0.4,
          "qty": 2.4,
          "repl": 1.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Cola",
          "orders": 523,
          "items": 526,
          "affected_orders": 8,
          "contribution": 0.4,
          "qty": 1.5,
          "repl": 0.6,
          "weight": 0,
          "price": 0
        }
      ],
      "SANTIM": [
        {
          "category": "Various, mixed",
          "orders": 729,
          "items": 1166,
          "affected_orders": 141,
          "contribution": 12.9,
          "qty": 11.7,
          "repl": 4.2,
          "weight": 2.0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "orders": 1092,
          "items": 2957,
          "affected_orders": 121,
          "contribution": 11.1,
          "qty": 4.0,
          "repl": 2.8,
          "weight": 0.9,
          "price": 0
        },
        {
          "category": "Shashlik",
          "orders": 214,
          "items": 192,
          "affected_orders": 57,
          "contribution": 5.2,
          "qty": 24.5,
          "repl": 7.8,
          "weight": 6.8,
          "price": 0
        },
        {
          "category": "Non-Food",
          "orders": 486,
          "items": 656,
          "affected_orders": 20,
          "contribution": 1.8,
          "qty": 3.2,
          "repl": 10.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Cola",
          "orders": 232,
          "items": 243,
          "affected_orders": 14,
          "contribution": 1.3,
          "qty": 5.8,
          "repl": 2.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Chips & Crackers",
          "orders": 84,
          "items": 116,
          "affected_orders": 10,
          "contribution": 0.9,
          "qty": 10.3,
          "repl": 1.7,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "orders": 300,
          "items": 328,
          "affected_orders": 9,
          "contribution": 0.8,
          "qty": 2.7,
          "repl": 0.9,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Snacks",
          "orders": 117,
          "items": 130,
          "affected_orders": 9,
          "contribution": 0.8,
          "qty": 6.2,
          "repl": 1.5,
          "weight": 0.8,
          "price": 0
        },
        {
          "category": "Orange",
          "orders": 72,
          "items": 61,
          "affected_orders": 9,
          "contribution": 0.8,
          "qty": 13.1,
          "repl": 0,
          "weight": 1.6,
          "price": 0
        },
        {
          "category": "Green Salad",
          "orders": 42,
          "items": 29,
          "affected_orders": 6,
          "contribution": 0.5,
          "qty": 20.7,
          "repl": 0,
          "weight": 3.4,
          "price": 0
        }
      ],
      "KOPIYKA MINI": [
        {
          "category": "Various, mixed",
          "orders": 840,
          "items": 1448,
          "affected_orders": 108,
          "contribution": 8.9,
          "qty": 8.4,
          "repl": 3.9,
          "weight": 0.2,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "orders": 1209,
          "items": 2549,
          "affected_orders": 105,
          "contribution": 8.6,
          "qty": 4.0,
          "repl": 3.3,
          "weight": 0.4,
          "price": 0
        },
        {
          "category": "Snacks",
          "orders": 158,
          "items": 169,
          "affected_orders": 27,
          "contribution": 2.2,
          "qty": 14.2,
          "repl": 6.5,
          "weight": 1.8,
          "price": 0
        },
        {
          "category": "Non-Food",
          "orders": 538,
          "items": 670,
          "affected_orders": 12,
          "contribution": 1.0,
          "qty": 1.9,
          "repl": 6.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Chips & Crackers",
          "orders": 126,
          "items": 137,
          "affected_orders": 11,
          "contribution": 0.9,
          "qty": 8.0,
          "repl": 2.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "orders": 240,
          "items": 268,
          "affected_orders": 10,
          "contribution": 0.8,
          "qty": 3.7,
          "repl": 2.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "orders": 75,
          "items": 69,
          "affected_orders": 8,
          "contribution": 0.7,
          "qty": 10.1,
          "repl": 4.3,
          "weight": 1.4,
          "price": 0
        },
        {
          "category": "Beef burger",
          "orders": 17,
          "items": 11,
          "affected_orders": 6,
          "contribution": 0.5,
          "qty": 63.6,
          "repl": 9.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Rosé Wine",
          "orders": 10,
          "items": 8,
          "affected_orders": 4,
          "contribution": 0.3,
          "qty": 50.0,
          "repl": 12.5,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Candies",
          "orders": 43,
          "items": 43,
          "affected_orders": 4,
          "contribution": 0.3,
          "qty": 9.3,
          "repl": 2.3,
          "weight": 0,
          "price": 0
        }
      ],
      "RODYNNA KOVBASKA": [
        {
          "category": "Shashlik",
          "orders": 217,
          "items": 373,
          "affected_orders": 76,
          "contribution": 29.7,
          "qty": 18.0,
          "repl": 4.8,
          "weight": 7.8,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "orders": 188,
          "items": 255,
          "affected_orders": 59,
          "contribution": 23.0,
          "qty": 28.2,
          "repl": 5.5,
          "weight": 4.7,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "orders": 181,
          "items": 208,
          "affected_orders": 19,
          "contribution": 7.4,
          "qty": 9.6,
          "repl": 1.9,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Snacks",
          "orders": 37,
          "items": 37,
          "affected_orders": 13,
          "contribution": 5.1,
          "qty": 32.4,
          "repl": 0,
          "weight": 8.1,
          "price": 0
        },
        {
          "category": "Ketchup",
          "orders": 23,
          "items": 11,
          "affected_orders": 12,
          "contribution": 4.7,
          "qty": 109.1,
          "repl": 9.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "orders": 13,
          "items": 8,
          "affected_orders": 7,
          "contribution": 2.7,
          "qty": 87.5,
          "repl": 12.5,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Honey Cake",
          "orders": 20,
          "items": 11,
          "affected_orders": 5,
          "contribution": 2.0,
          "qty": 45.5,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Mayonnaise",
          "orders": 13,
          "items": 7,
          "affected_orders": 4,
          "contribution": 1.6,
          "qty": 57.1,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Ribs",
          "orders": 12,
          "items": 10,
          "affected_orders": 3,
          "contribution": 1.2,
          "qty": 20.0,
          "repl": 10.0,
          "weight": 10.0,
          "price": 0
        },
        {
          "category": "Cupcake",
          "orders": 9,
          "items": 7,
          "affected_orders": 3,
          "contribution": 1.2,
          "qty": 42.9,
          "repl": 0,
          "weight": 0,
          "price": 0
        }
      ]
    },
    "skus": {
      "CAFE RYNOK": [
        {
          "category": "Various, mixed",
          "sku": "000005721",
          "name": "Салат Олівє з копченою куркою 250г",
          "orders": 307,
          "items": 260,
          "affected_orders": 26,
          "qty": 10.0,
          "repl": 2.7,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "000018980",
          "name": "Курячий шніцель з картопляним пюре 320г",
          "orders": 236,
          "items": 192,
          "affected_orders": 23,
          "qty": 12.0,
          "repl": 6.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000016423",
          "name": "Крученик з сиром чедер та картопляним пюре 250г",
          "orders": 252,
          "items": 206,
          "affected_orders": 22,
          "qty": 10.7,
          "repl": 5.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000018975",
          "name": "Міні салат з крабами та кукурудзою 180г",
          "orders": 259,
          "items": 220,
          "affected_orders": 19,
          "qty": 8.6,
          "repl": 2.7,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "000020020",
          "name": "Курячий шніцель з гречкою та грибами 290г",
          "orders": 169,
          "items": 135,
          "affected_orders": 16,
          "qty": 11.9,
          "repl": 7.4,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "000020023",
          "name": "Котлета по-Київськи з картоплею та зеленню 270г",
          "orders": 327,
          "items": 281,
          "affected_orders": 11,
          "qty": 3.9,
          "repl": 5.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "000013865",
          "name": "Локшина з куркою в кислосолодкому соусі 450г",
          "orders": 141,
          "items": 119,
          "affected_orders": 9,
          "qty": 7.6,
          "repl": 2.5,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Carbonara",
          "sku": "000006977",
          "name": "Паста Карбонара 320г",
          "orders": 113,
          "items": 86,
          "affected_orders": 8,
          "qty": 9.3,
          "repl": 7.0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "000020438",
          "name": "Курячі котлетки з картопляним пюре та овочами 280г",
          "orders": 147,
          "items": 127,
          "affected_orders": 8,
          "qty": 6.3,
          "repl": 3.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000018214",
          "name": "Гречка з тунцем і яйцем 290г",
          "orders": 82,
          "items": 70,
          "affected_orders": 8,
          "qty": 11.4,
          "repl": 1.4,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000020030",
          "name": "Локшина з креветкою та овочами 420г",
          "orders": 140,
          "items": 120,
          "affected_orders": 7,
          "qty": 5.8,
          "repl": 4.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000007664",
          "name": "Борщ зелений + сметана 250/30г",
          "orders": 173,
          "items": 155,
          "affected_orders": 7,
          "qty": 4.5,
          "repl": 1.9,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000004918",
          "name": "Паштейш ko pasteis шт",
          "orders": 104,
          "items": 83,
          "affected_orders": 7,
          "qty": 8.4,
          "repl": 3.6,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000010460",
          "name": "Рис з яйцем тамаго та куркою 330г",
          "orders": 201,
          "items": 174,
          "affected_orders": 7,
          "qty": 4.0,
          "repl": 1.7,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000015945",
          "name": "Міні салат з молодої капусти 150г",
          "orders": 129,
          "items": 104,
          "affected_orders": 7,
          "qty": 6.7,
          "repl": 1.9,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "000018659",
          "name": "Млинці з шинкою та чедером 4шт 380г",
          "orders": 83,
          "items": 71,
          "affected_orders": 7,
          "qty": 9.9,
          "repl": 2.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "000020437",
          "name": "Рибні котлетки з картопляним пюре та томатною сальсою 270г",
          "orders": 77,
          "items": 66,
          "affected_orders": 7,
          "qty": 10.6,
          "repl": 3.0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Caesar Salad",
          "sku": "000017414",
          "name": "Салат Цезар з куркою кріспі +соус Цезар + крутони 215/40/5г",
          "orders": 116,
          "items": 94,
          "affected_orders": 6,
          "qty": 6.4,
          "repl": 5.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "000020501",
          "name": "Рибні котлетки з кабачком та печеними овочами 320г",
          "orders": 68,
          "items": 56,
          "affected_orders": 6,
          "qty": 10.7,
          "repl": 7.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Nigiri",
          "sku": "000019364",
          "name": "Онігірі з лососем та крем сиром 140г",
          "orders": 103,
          "items": 87,
          "affected_orders": 6,
          "qty": 6.9,
          "repl": 2.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000020626",
          "name": "Млинці з маком та соусом три молока 350г",
          "orders": 102,
          "items": 88,
          "affected_orders": 6,
          "qty": 6.8,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "000018120",
          "name": "Пуф Zelen' снікерс шт.",
          "orders": 46,
          "items": 36,
          "affected_orders": 6,
          "qty": 16.7,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Cola",
          "sku": "000001650",
          "name": "Напій б/а Coca-Cola zero 0,33л з/б",
          "orders": 74,
          "items": 66,
          "affected_orders": 6,
          "qty": 9.1,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "000019815",
          "name": "Боул з картоплею та куркою 270г",
          "orders": 157,
          "items": 132,
          "affected_orders": 5,
          "qty": 3.8,
          "repl": 4.5,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000020074",
          "name": "Паста болоньєзе з куркою 320г",
          "orders": 131,
          "items": 106,
          "affected_orders": 5,
          "qty": 4.7,
          "repl": 3.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000017926",
          "name": "Млинці з тунцем шпинатні 4шт 360г",
          "orders": 74,
          "items": 58,
          "affected_orders": 5,
          "qty": 8.6,
          "repl": 5.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Nigiri",
          "sku": "000019346",
          "name": "Онігірі з креветкою 140г",
          "orders": 96,
          "items": 80,
          "affected_orders": 5,
          "qty": 6.3,
          "repl": 3.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000018129",
          "name": "Міні салат оселедець під шубою 200г",
          "orders": 126,
          "items": 113,
          "affected_orders": 5,
          "qty": 4.4,
          "repl": 1.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000020417",
          "name": "Кабачкові палички з соусом дзадзикі 250/30г",
          "orders": 70,
          "items": 62,
          "affected_orders": 5,
          "qty": 8.1,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "000006972",
          "name": "Паста Чікен Песто 310г",
          "orders": 112,
          "items": 93,
          "affected_orders": 4,
          "qty": 4.3,
          "repl": 10.8,
          "weight": 0,
          "price": 0
        }
      ],
      "KOPIYKA": [
        {
          "category": "Grocery Food",
          "sku": "7969",
          "name": "Банан (за 500 г.)",
          "orders": 236,
          "items": 209,
          "affected_orders": 38,
          "qty": 4.3,
          "repl": 0.5,
          "weight": 13.9,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "12607",
          "name": "Гомiлка куряча 4кг охол. (за 500 г.)",
          "orders": 55,
          "items": 46,
          "affected_orders": 32,
          "qty": 8.7,
          "repl": 0,
          "weight": 60.9,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "33250",
          "name": "Морква молода (за 200 г.)",
          "orders": 71,
          "items": 58,
          "affected_orders": 21,
          "qty": 10.3,
          "repl": 3.4,
          "weight": 25.9,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "86528",
          "name": "Огірок короткоплідний Україна (за 300 г.)",
          "orders": 209,
          "items": 193,
          "affected_orders": 20,
          "qty": 3.6,
          "repl": 0.5,
          "weight": 6.7,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "22176",
          "name": "Помiдори Утконосівка (за 100 г.)",
          "orders": 79,
          "items": 63,
          "affected_orders": 16,
          "qty": 11.1,
          "repl": 11.1,
          "weight": 14.3,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "35043",
          "name": "Кавун (за 500 г.)",
          "orders": 61,
          "items": 52,
          "affected_orders": 16,
          "qty": 13.5,
          "repl": 1.9,
          "weight": 17.3,
          "price": 0
        },
        {
          "category": "Snacks",
          "sku": "187818",
          "name": "Сосиска в тісті власне вир-во",
          "orders": 30,
          "items": 14,
          "affected_orders": 13,
          "qty": 92.9,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "50525",
          "name": "Цибуля молода (за 300 г.)",
          "orders": 117,
          "items": 113,
          "affected_orders": 12,
          "qty": 0,
          "repl": 0.9,
          "weight": 10.6,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "140526",
          "name": "Хліб французький бездріжд. 370г власне вир-во",
          "orders": 48,
          "items": 32,
          "affected_orders": 12,
          "qty": 37.5,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "206674",
          "name": "Піца  130г 4 мяса куточок",
          "orders": 29,
          "items": 15,
          "affected_orders": 10,
          "qty": 66.7,
          "repl": 6.7,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "180066",
          "name": "Яйце куряче Пані Цінна 10шт 1кат",
          "orders": 59,
          "items": 46,
          "affected_orders": 9,
          "qty": 19.6,
          "repl": 10.9,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "sku": "1195",
          "name": "Вода Поляна квасова 1.5л мінеральна",
          "orders": 85,
          "items": 70,
          "affected_orders": 9,
          "qty": 12.9,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "95076",
          "name": "Помідори Україна червоні польові (за 100 г.)",
          "orders": 31,
          "items": 29,
          "affected_orders": 9,
          "qty": 3.4,
          "repl": 0,
          "weight": 27.6,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "17860",
          "name": "Картопля фермерська біла (за 500 г.)",
          "orders": 52,
          "items": 40,
          "affected_orders": 8,
          "qty": 20.0,
          "repl": 12.5,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Cola",
          "sku": "212578",
          "name": "Вода Пепсі-кола 1.75л блек",
          "orders": 94,
          "items": 77,
          "affected_orders": 8,
          "qty": 10.4,
          "repl": 3.9,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "174878",
          "name": "Салат Олів'є уп",
          "orders": 34,
          "items": 23,
          "affected_orders": 8,
          "qty": 34.8,
          "repl": 4.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "196222",
          "name": "Молоко Яготинське 900мл 2.6% т.ф",
          "orders": 23,
          "items": 13,
          "affected_orders": 8,
          "qty": 61.5,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "177097",
          "name": "Котлета куряча х картопляне пюре уп К21",
          "orders": 36,
          "items": 24,
          "affected_orders": 8,
          "qty": 33.3,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "96065",
          "name": "Помідори Україна червоні (за 300 г.)",
          "orders": 34,
          "items": 29,
          "affected_orders": 7,
          "qty": 3.4,
          "repl": 6.9,
          "weight": 20.7,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "77216",
          "name": "Диня Дністровська (за 100 г.)",
          "orders": 18,
          "items": 14,
          "affected_orders": 7,
          "qty": 14.3,
          "repl": 7.1,
          "weight": 35.7,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "5688",
          "name": "Картопля молода рожева (за 100 г.)",
          "orders": 30,
          "items": 25,
          "affected_orders": 7,
          "qty": 4.0,
          "repl": 4.0,
          "weight": 24.0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "80258",
          "name": "Лимон (за 200 г.)",
          "orders": 78,
          "items": 69,
          "affected_orders": 7,
          "qty": 1.4,
          "repl": 1.4,
          "weight": 8.7,
          "price": 0
        },
        {
          "category": "Still water",
          "sku": "159848",
          "name": "Вода Buvette 1.5л №7 с.г",
          "orders": 53,
          "items": 43,
          "affected_orders": 7,
          "qty": 16.3,
          "repl": 2.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "167448",
          "name": "С.алк.напій Revo 0.5л 8.5%",
          "orders": 49,
          "items": 42,
          "affected_orders": 7,
          "qty": 16.7,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "21887",
          "name": "Фiле куряче 4кг охол. (за 300 г.)",
          "orders": 65,
          "items": 52,
          "affected_orders": 6,
          "qty": 5.8,
          "repl": 7.7,
          "weight": 5.8,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "76884",
          "name": "Картопля молода Тірас (за 100 г.)",
          "orders": 30,
          "items": 24,
          "affected_orders": 6,
          "qty": 8.3,
          "repl": 8.3,
          "weight": 16.7,
          "price": 0
        },
        {
          "category": "Cola",
          "sku": "212577",
          "name": "Вода Пепсі-кола 1.75л",
          "orders": 146,
          "items": 128,
          "affected_orders": 6,
          "qty": 4.7,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "16493",
          "name": "Помідори Туреччина червоні (за 300 г.)",
          "orders": 24,
          "items": 14,
          "affected_orders": 6,
          "qty": 35.7,
          "repl": 0,
          "weight": 7.1,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "176939",
          "name": "Морозиво Белая бяроза 77г пломбір ваф цукр с",
          "orders": 22,
          "items": 17,
          "affected_orders": 6,
          "qty": 35.3,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "45396",
          "name": "Крило плечового частина ох (за 500 г.)",
          "orders": 12,
          "items": 10,
          "affected_orders": 6,
          "qty": 20.0,
          "repl": 0,
          "weight": 40.0,
          "price": 0
        }
      ],
      "KOPIYKA MINI": [
        {
          "category": "Still water",
          "sku": "1195",
          "name": "Вода Поляна квасова 1.5л мінеральна",
          "orders": 24,
          "items": 19,
          "affected_orders": 4,
          "qty": 21.1,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "167448",
          "name": "С.алк.напій Revo 0.5л 8.5%",
          "orders": 25,
          "items": 20,
          "affected_orders": 3,
          "qty": 15.0,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "7969",
          "name": "Банан (за 500 г.)",
          "orders": 22,
          "items": 20,
          "affected_orders": 2,
          "qty": 0,
          "repl": 5.0,
          "weight": 10.0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "18990",
          "name": "ПАКЕТ Копійка 33*50",
          "orders": 13,
          "items": 11,
          "affected_orders": 1,
          "qty": 9.1,
          "repl": 81.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "199781",
          "name": "Пакет надтонкий",
          "orders": 29,
          "items": 29,
          "affected_orders": 0,
          "qty": 0,
          "repl": 100.0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "50596",
          "name": "ПАКЕТ Копійка 27*45",
          "orders": 23,
          "items": 24,
          "affected_orders": 0,
          "qty": 0,
          "repl": 95.8,
          "weight": 0,
          "price": 0
        }
      ],
      "RODYNNA KOVBASKA": [
        {
          "category": "Various, mixed",
          "sku": "20006",
          "name": "{\"uk-UA\":\"Філе з курятини (за 500 г)\"}",
          "orders": 32,
          "items": 24,
          "affected_orders": 11,
          "qty": 29.2,
          "repl": 4.2,
          "weight": 16.7,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "20136",
          "name": "{\"uk-UA\":\"Фарш курячий (за 500 г)\"}",
          "orders": 16,
          "items": 15,
          "affected_orders": 5,
          "qty": 0,
          "repl": 0,
          "weight": 33.3,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "31023",
          "name": "{\"uk-UA\":\"Чіабата\"}",
          "orders": 20,
          "items": 17,
          "affected_orders": 4,
          "qty": 23.5,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "53062",
          "name": "{\"uk-UA\":\"Яйце куряче 10шт.\"}",
          "orders": 20,
          "items": 13,
          "affected_orders": 4,
          "qty": 30.8,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "54133",
          "name": "{\"uk-UA\":\"Молоко коров’яче 3,6% 0,9 л\"}",
          "orders": 18,
          "items": 16,
          "affected_orders": 2,
          "qty": 12.5,
          "repl": 12.5,
          "weight": 0,
          "price": 0
        }
      ],
      "RUKAVYCHKA": [
        {
          "category": "Grocery Food",
          "sku": "1102030227",
          "name": "КРІП ВАГ  УКРЗЕЛЕНЬ (за 100г)",
          "orders": 44,
          "items": 31,
          "affected_orders": 24,
          "qty": 19.4,
          "repl": 0,
          "weight": 58.1,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1101020013",
          "name": "ПОМІДОРИ 1КГ (за 100г)",
          "orders": 122,
          "items": 94,
          "affected_orders": 14,
          "qty": 13.8,
          "repl": 1.1,
          "weight": 1.1,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "2301011397",
          "name": "Вир Тют Д/Ел Наг Silver 1Пач Terea",
          "orders": 74,
          "items": 66,
          "affected_orders": 13,
          "qty": 19.7,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1102030226",
          "name": "ЦИБУЛЯ ЗЕЛЕНА ВАГ  УКРЗЕЛЕНЬ (за 100г)",
          "orders": 33,
          "items": 26,
          "affected_orders": 12,
          "qty": 3.8,
          "repl": 0,
          "weight": 42.3,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1101010371",
          "name": "БАНАН 1КГ (за 100г)",
          "orders": 209,
          "items": 186,
          "affected_orders": 8,
          "qty": 2.7,
          "repl": 0,
          "weight": 1.6,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1101020014",
          "name": "ОГІРКИ КОРНІШОНИ 1КГ (за 100г)",
          "orders": 147,
          "items": 132,
          "affected_orders": 8,
          "qty": 6.1,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1102030228",
          "name": "ПЕТРУШКА ВАГ  УКРЗЕЛЕНЬ (за 100г)",
          "orders": 18,
          "items": 14,
          "affected_orders": 6,
          "qty": 0,
          "repl": 0,
          "weight": 42.9,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1504010183",
          "name": "Молоко Паст 2.5% Пет 870Г Простонаше",
          "orders": 37,
          "items": 35,
          "affected_orders": 6,
          "qty": 17.1,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "0302010006",
          "name": "ФІЛЕ КУРЯЧЕ 1 КГ (за 100г)",
          "orders": 92,
          "items": 80,
          "affected_orders": 5,
          "qty": 5.0,
          "repl": 2.5,
          "weight": 1.3,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1801010692",
          "name": "Корм Д/Котiв Курка В Желе 85Г Віскас",
          "orders": 14,
          "items": 13,
          "affected_orders": 5,
          "qty": 38.5,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "0207000107",
          "name": "Енерг Напiй Boost Ж/Б 0.5Л Non Stop",
          "orders": 19,
          "items": 13,
          "affected_orders": 5,
          "qty": 38.5,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1101020434",
          "name": "МОРКВА МИТА ВАГ (за 100г)",
          "orders": 23,
          "items": 20,
          "affected_orders": 5,
          "qty": 10.0,
          "repl": 0,
          "weight": 15.0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "2301011393",
          "name": "Вир Тют Д/Ел Наг Turquoise 1Пач Terea",
          "orders": 50,
          "items": 46,
          "affected_orders": 5,
          "qty": 10.9,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "0302060053",
          "name": "ФАРШ КУРЯЧИЙ ОСОБЛИВИЙ ОХОЛОДЖЕНИЙ 1КГ (за 100г)",
          "orders": 38,
          "items": 30,
          "affected_orders": 5,
          "qty": 16.7,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1101010048",
          "name": "КАВУН 1КГ (за 100г)",
          "orders": 40,
          "items": 28,
          "affected_orders": 4,
          "qty": 7.1,
          "repl": 0,
          "weight": 7.1,
          "price": 0
        },
        {
          "category": "Beef burger",
          "sku": "0312000051",
          "name": "ГАМБУРГЕР З  КОТЛЕТОЮ 230Г TO GO",
          "orders": 44,
          "items": 38,
          "affected_orders": 4,
          "qty": 10.5,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Wheat Beer",
          "sku": "0104010231",
          "name": "Пиво Світл Koryfei Expor 4.2% Ж/Б 0.5Л Опілля",
          "orders": 14,
          "items": 14,
          "affected_orders": 4,
          "qty": 28.6,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "0301010002",
          "name": "ШИНКА СВИННА 1 КГ (за 100г)",
          "orders": 27,
          "items": 22,
          "affected_orders": 3,
          "qty": 9.1,
          "repl": 9.1,
          "weight": 4.5,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "2301011391",
          "name": "Вир Тют Д/Ел Наг Blossom Wave 1Пач Terea",
          "orders": 34,
          "items": 31,
          "affected_orders": 3,
          "qty": 9.7,
          "repl": 3.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "2301011390",
          "name": "Вир Тют Д/Ел Наг Sun Pearl 1Пач Terea",
          "orders": 30,
          "items": 25,
          "affected_orders": 3,
          "qty": 12.0,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "0307020483",
          "name": "БУЛКА З СОСИСКОЮ 80Г КУХАРОЧКА",
          "orders": 26,
          "items": 17,
          "affected_orders": 3,
          "qty": 17.6,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "0104030022",
          "name": "Пиво Світле Міцне 8% 1Л Арсенал",
          "orders": 15,
          "items": 10,
          "affected_orders": 3,
          "qty": 30.0,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "1403010747",
          "name": "Мороз Ескiмо Пломбiр 1965 80Г Лімо",
          "orders": 16,
          "items": 11,
          "affected_orders": 3,
          "qty": 27.3,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Chips & Crackers",
          "sku": "0802010873",
          "name": "Чипси Карт Смак Краба 120Г Lays",
          "orders": 22,
          "items": 16,
          "affected_orders": 3,
          "qty": 18.8,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Mushroom Pizza",
          "sku": "0307020664",
          "name": "Піца Шинка/Гриби 188Г Кухарочка",
          "orders": 25,
          "items": 19,
          "affected_orders": 3,
          "qty": 15.8,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "2301011392",
          "name": "Вир Тют Д/Ел Наг Purple Wave 1Пач Terea",
          "orders": 39,
          "items": 34,
          "affected_orders": 3,
          "qty": 8.8,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1101020067",
          "name": "ПЕРЕЦЬ БОЛГАРСЬКИЙ СОЛОДКИЙ ЧЕРВОНИЙ 1КГ (за 100г)",
          "orders": 52,
          "items": 47,
          "affected_orders": 3,
          "qty": 0,
          "repl": 0,
          "weight": 6.4,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "1101010381",
          "name": "ЛИМОН 1КАТЕГОРІЇ 1КГ (за 100г)",
          "orders": 55,
          "items": 52,
          "affected_orders": 3,
          "qty": 0,
          "repl": 0,
          "weight": 5.8,
          "price": 0
        },
        {
          "category": "Sparkling Water",
          "sku": "0202020333",
          "name": "Мін Вода N7 Лікув/Стол Сил/Газ 1.5Л Buvette",
          "orders": 18,
          "items": 15,
          "affected_orders": 3,
          "qty": 20.0,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "1801010600",
          "name": "Корм Д/Котiв Океаніч Риба В Соус 85Г Sheba",
          "orders": 11,
          "items": 10,
          "affected_orders": 3,
          "qty": 30.0,
          "repl": 0,
          "weight": 0,
          "price": 0
        }
      ],
      "SANTIM": [
        {
          "category": "Various, mixed",
          "sku": "14067",
          "name": "Фiле куряче охол. (за 300 г.)",
          "orders": 33,
          "items": 29,
          "affected_orders": 7,
          "qty": 0,
          "repl": 3.4,
          "weight": 24.1,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "2216",
          "name": "Свинина челогач (за 500 г.)",
          "orders": 34,
          "items": 19,
          "affected_orders": 6,
          "qty": 31.6,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Liqueurs",
          "sku": "205112",
          "name": "Лікер Amaro Alpen Krauter 0.7л",
          "orders": 21,
          "items": 17,
          "affected_orders": 5,
          "qty": 29.4,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Cola",
          "sku": "212578",
          "name": "Вода Пепсі-кола 1.75л блек",
          "orders": 39,
          "items": 31,
          "affected_orders": 5,
          "qty": 16.1,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "120521",
          "name": "Хлiб Нове діло 500г домашнi в.с",
          "orders": 17,
          "items": 12,
          "affected_orders": 4,
          "qty": 33.3,
          "repl": 8.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "89905",
          "name": "Вода Грузинський букет 0.5л лимонад тархун",
          "orders": 19,
          "items": 15,
          "affected_orders": 4,
          "qty": 26.7,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "35043",
          "name": "Кавун (за 500 г.)",
          "orders": 20,
          "items": 16,
          "affected_orders": 3,
          "qty": 6.3,
          "repl": 0,
          "weight": 12.5,
          "price": 0
        },
        {
          "category": "Still water",
          "sku": "99297",
          "name": "Вода Аквуля 2л дитяча",
          "orders": 55,
          "items": 48,
          "affected_orders": 3,
          "qty": 6.3,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "sku": "155413",
          "name": "Вода Карпатська Джерельна 2л н.г",
          "orders": 16,
          "items": 13,
          "affected_orders": 3,
          "qty": 23.1,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "86919",
          "name": "Полуниця фермерська (за 100 г.)",
          "orders": 42,
          "items": 35,
          "affected_orders": 3,
          "qty": 5.7,
          "repl": 0,
          "weight": 2.9,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "8369",
          "name": "Філе д.відбивної кур.бр.охл Наша Ряба (за 300 г.)",
          "orders": 43,
          "items": 34,
          "affected_orders": 3,
          "qty": 0,
          "repl": 0,
          "weight": 8.8,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "174250",
          "name": "Пиво Kalnapilis Royal Select 0.568 л  з б",
          "orders": 20,
          "items": 18,
          "affected_orders": 3,
          "qty": 16.7,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "33179",
          "name": "Картопля молода (за 300 г.)",
          "orders": 31,
          "items": 26,
          "affected_orders": 2,
          "qty": 3.8,
          "repl": 15.4,
          "weight": 3.8,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "33250",
          "name": "Морква молода (за 200 г.)",
          "orders": 13,
          "items": 10,
          "affected_orders": 2,
          "qty": 10.0,
          "repl": 20.0,
          "weight": 10.0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "76884",
          "name": "Картопля молода Тірас (за 100 г.)",
          "orders": 10,
          "items": 10,
          "affected_orders": 1,
          "qty": 0,
          "repl": 20.0,
          "weight": 10.0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "199781",
          "name": "Пакет надтонкий",
          "orders": 39,
          "items": 39,
          "affected_orders": 0,
          "qty": 0,
          "repl": 97.4,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "122413",
          "name": "ПАКЕТ См 44*65",
          "orders": 32,
          "items": 32,
          "affected_orders": 0,
          "qty": 0,
          "repl": 96.9,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "200239",
          "name": "Пакет біорозкладний",
          "orders": 26,
          "items": 26,
          "affected_orders": 0,
          "qty": 0,
          "repl": 100.0,
          "weight": 0,
          "price": 0
        }
      ],
      "TAISTRA": [
        {
          "category": "Grocery Food",
          "sku": "24377",
          "name": "Банан . (за 100 г)",
          "orders": 179,
          "items": 151,
          "affected_orders": 15,
          "qty": 9.3,
          "repl": 0,
          "weight": 0.7,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "31279",
          "name": "Хліб КИЇВ ХЛІБ тост світлий різ. 350г",
          "orders": 85,
          "items": 65,
          "affected_orders": 14,
          "qty": 21.5,
          "repl": 1.5,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "23270",
          "name": "Яйце КВОЧКА куряче С1 фасовані 10шт",
          "orders": 122,
          "items": 95,
          "affected_orders": 11,
          "qty": 11.6,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "42872",
          "name": "Хліб НАДЗБРУЧЧЯ ХЛІБ пшенично житній подовий половинка різаний 350г",
          "orders": 24,
          "items": 12,
          "affected_orders": 7,
          "qty": 58.3,
          "repl": 25.0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "24402",
          "name": "Кавун (за 100 г)",
          "orders": 32,
          "items": 21,
          "affected_orders": 7,
          "qty": 28.6,
          "repl": 0,
          "weight": 4.8,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "24407",
          "name": "Капуста молода (за 100 г)",
          "orders": 29,
          "items": 21,
          "affected_orders": 7,
          "qty": 28.6,
          "repl": 0,
          "weight": 4.8,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "23560",
          "name": "Морозиво ЛАСУНКА сік світлофор 95г",
          "orders": 22,
          "items": 13,
          "affected_orders": 6,
          "qty": 46.2,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "23268",
          "name": "Яйце КВОЧКА куряче С0 фасовані дом. 10шт",
          "orders": 22,
          "items": 15,
          "affected_orders": 5,
          "qty": 33.3,
          "repl": 13.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "43053",
          "name": "Батон ПЕРШИЙ ХЛІБ звичайний різаний уп. 500г.",
          "orders": 27,
          "items": 20,
          "affected_orders": 5,
          "qty": 25.0,
          "repl": 10.0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "102149",
          "name": "Батон ПЕРШИЙ ХЛІБ молочний різаний 450г уп.",
          "orders": 19,
          "items": 11,
          "affected_orders": 5,
          "qty": 45.5,
          "repl": 9.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "32511",
          "name": "Батон РУМЯНЕЦЬ  на черені різ. 400г",
          "orders": 35,
          "items": 29,
          "affected_orders": 5,
          "qty": 17.2,
          "repl": 3.4,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "sku": "27867",
          "name": "Вода ДЕВАЙТІС сильногазована 2л ПЕТ",
          "orders": 43,
          "items": 36,
          "affected_orders": 5,
          "qty": 13.9,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "59525",
          "name": "Шинка ГЛОБИНО фует в/с, в/п нар.серв. 105 г",
          "orders": 80,
          "items": 64,
          "affected_orders": 5,
          "qty": 7.8,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "44694",
          "name": "Батон ПЕРШИЙ ХЛІБ гірчичний уп 400г",
          "orders": 34,
          "items": 24,
          "affected_orders": 4,
          "qty": 16.7,
          "repl": 12.5,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "24448",
          "name": "Огірок колючий (за 100 г)",
          "orders": 161,
          "items": 141,
          "affected_orders": 4,
          "qty": 2.1,
          "repl": 0.7,
          "weight": 0.7,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "24496",
          "name": "Гриби Печериці (за 100 г)",
          "orders": 24,
          "items": 20,
          "affected_orders": 4,
          "qty": 20.0,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Vodka",
          "sku": "10794",
          "name": "Горілка GREEN DAY 0,7л (Україна)",
          "orders": 27,
          "items": 22,
          "affected_orders": 4,
          "qty": 18.2,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Wheat Beer",
          "sku": "67948",
          "name": "Пиво ЧЕРНІГІВСЬКЕ біле 0,9л",
          "orders": 31,
          "items": 28,
          "affected_orders": 4,
          "qty": 14.3,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "108170",
          "name": "Хліб РУМЯНЕЦЬ заварний різаний 600г",
          "orders": 19,
          "items": 14,
          "affected_orders": 3,
          "qty": 21.4,
          "repl": 14.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "64840",
          "name": "Помідор сливка (за 100 г)",
          "orders": 33,
          "items": 24,
          "affected_orders": 3,
          "qty": 12.5,
          "repl": 4.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "44804",
          "name": "Яйце КВОЧКА куряче XL СВ фасовані 10шт",
          "orders": 23,
          "items": 17,
          "affected_orders": 3,
          "qty": 17.6,
          "repl": 5.9,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "24432",
          "name": "Лимон . (за 100 г)",
          "orders": 32,
          "items": 28,
          "affected_orders": 3,
          "qty": 10.7,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Wheat Beer",
          "sku": "25878",
          "name": "Пиво HIKE Blanche 0.5л з/б",
          "orders": 22,
          "items": 20,
          "affected_orders": 3,
          "qty": 15.0,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "74422",
          "name": "Пиво TUBORG Green 0.5л ж/б",
          "orders": 28,
          "items": 28,
          "affected_orders": 3,
          "qty": 10.7,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Non-Food",
          "sku": "130744",
          "name": "Sticks TEREA blue 1 пачка.",
          "orders": 22,
          "items": 20,
          "affected_orders": 3,
          "qty": 15.0,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "68838",
          "name": "Ковбаса с/к РАНЧО золота 1с 75г",
          "orders": 23,
          "items": 16,
          "affected_orders": 3,
          "qty": 18.8,
          "repl": 0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "24468",
          "name": "Помідори Туреччина . (за 100 г)",
          "orders": 28,
          "items": 23,
          "affected_orders": 2,
          "qty": 8.7,
          "repl": 4.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "23575",
          "name": "Морозиво РУДЬ 100% 500г",
          "orders": 17,
          "items": 14,
          "affected_orders": 2,
          "qty": 14.3,
          "repl": 7.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "74454",
          "name": "Квас ТАРАС Чорний 0.5л ж/б",
          "orders": 18,
          "items": 16,
          "affected_orders": 2,
          "qty": 12.5,
          "repl": 6.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Chips & Crackers",
          "sku": "47129",
          "name": "Чипси LAYS Краб 120г",
          "orders": 31,
          "items": 26,
          "affected_orders": 2,
          "qty": 7.7,
          "repl": 3.8,
          "weight": 0,
          "price": 0
        }
      ],
      "VARUS": [
        {
          "category": "Cola",
          "sku": "2652100",
          "name": "{\"uk-UA\":\"Напій Coca-Cola Zero 1.75 л\"}",
          "orders": 1005,
          "items": 669,
          "affected_orders": 246,
          "qty": 36.8,
          "repl": 7.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Cola",
          "sku": "2636742",
          "name": "{\"uk-UA\":\"Напій Coca-Cola сильногазований 1.75л\"}",
          "orders": 1607,
          "items": 1223,
          "affected_orders": 233,
          "qty": 19.1,
          "repl": 5.2,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "2610685",
          "name": "{\"uk-UA\":\"Огірок салатний Україна, ваговий 100г\"}",
          "orders": 1487,
          "items": 1178,
          "affected_orders": 211,
          "qty": 14.5,
          "repl": 1.3,
          "weight": 3.4,
          "price": 0
        },
        {
          "category": "Cola",
          "sku": "2651041",
          "name": "{\"uk-UA\":\"Напій Pepsi Блек безкалорійний сильногазований 1.75 л\"}",
          "orders": 730,
          "items": 487,
          "affected_orders": 185,
          "qty": 38.0,
          "repl": 10.7,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "sku": "2639267",
          "name": "{\"uk-UA\":\"Вода питна Varto Aqua Миргород природна негазована 6 л\"}",
          "orders": 430,
          "items": 251,
          "affected_orders": 140,
          "qty": 55.8,
          "repl": 14.3,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "177794",
          "name": "{\"uk-UA\":\"Окрошка з куркою, вагова 100г\"}",
          "orders": 274,
          "items": 126,
          "affected_orders": 134,
          "qty": 92.1,
          "repl": 4.8,
          "weight": 14.3,
          "price": 0
        },
        {
          "category": "Cola",
          "sku": "2646871",
          "name": "{\"uk-UA\":\"Напій Pepsi 1,75 л\"}",
          "orders": 756,
          "items": 575,
          "affected_orders": 121,
          "qty": 21.0,
          "repl": 13.0,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "2620692",
          "name": "{\"uk-UA\":\"Тортилья Цезар з куркою 280 г\"}",
          "orders": 227,
          "items": 81,
          "affected_orders": 115,
          "qty": 142.0,
          "repl": 3.7,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "2490537",
          "name": "{\"uk-UA\":\"Самса з куркою та цибулею 100г\"}",
          "orders": 191,
          "items": 66,
          "affected_orders": 113,
          "qty": 156.1,
          "repl": 12.1,
          "weight": 15.2,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "127622",
          "name": "{\"uk-UA\":\"Банан ваговий 500г\"}",
          "orders": 1477,
          "items": 1300,
          "affected_orders": 113,
          "qty": 3.8,
          "repl": 0.4,
          "weight": 4.9,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "2544821",
          "name": "{\"uk-UA\":\"Перець червоний ваговий 250г\"}",
          "orders": 566,
          "items": 427,
          "affected_orders": 106,
          "qty": 15.5,
          "repl": 1.2,
          "weight": 9.4,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "2507408",
          "name": "{\"uk-UA\":\"Огірок тепличний ваговий 500г\"}",
          "orders": 664,
          "items": 516,
          "affected_orders": 101,
          "qty": 16.3,
          "repl": 8.1,
          "weight": 3.3,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "2607202",
          "name": "{\"uk-UA\":\"Піца з мисливськими ковбасками 500г\"}",
          "orders": 584,
          "items": 409,
          "affected_orders": 101,
          "qty": 24.7,
          "repl": 5.6,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Still water",
          "sku": "2656406",
          "name": "{\"uk-UA\":\"Вода Вигода негазована 5 л\"}",
          "orders": 410,
          "items": 286,
          "affected_orders": 100,
          "qty": 35.0,
          "repl": 10.5,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "194127",
          "name": "{\"uk-UA\":\"Пиріжок з картоплею ваговий 100г\"}",
          "orders": 189,
          "items": 90,
          "affected_orders": 100,
          "qty": 87.8,
          "repl": 23.3,
          "weight": 23.3,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "2618168",
          "name": "{\"uk-UA\":\"Борщ по-домашньому з м'ясом ваговий 100г\"}",
          "orders": 297,
          "items": 177,
          "affected_orders": 100,
          "qty": 52.0,
          "repl": 6.2,
          "weight": 4.5,
          "price": 0
        },
        {
          "category": "Cola",
          "sku": "2578514",
          "name": "{\"uk-UA\":\"Напій Coca-Cola Zero сильногазований 1.25 л\"}",
          "orders": 457,
          "items": 330,
          "affected_orders": 97,
          "qty": 29.4,
          "repl": 34.5,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "2627131",
          "name": "{\"uk-UA\":\"Піца Три м'яса 500 г\"}",
          "orders": 670,
          "items": 492,
          "affected_orders": 97,
          "qty": 19.7,
          "repl": 7.1,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "136329",
          "name": "{\"uk-UA\":\"Салат з курячим філе і томатами ваговий 100г\"}",
          "orders": 412,
          "items": 296,
          "affected_orders": 90,
          "qty": 27.4,
          "repl": 6.4,
          "weight": 3.0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "2627130",
          "name": "{\"uk-UA\":\"Піца Пікантна з куркою та грудинкою 500 г\"}",
          "orders": 648,
          "items": 485,
          "affected_orders": 88,
          "qty": 18.1,
          "repl": 6.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Chips & Crackers",
          "sku": "2657863",
          "name": "{\"uk-UA\":\"Чипси Золотисті картопляні зі смаком чорної ікри 100 г\"}",
          "orders": 223,
          "items": 115,
          "affected_orders": 86,
          "qty": 74.8,
          "repl": 2.6,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Shashlik",
          "sku": "2507659",
          "name": "{\"uk-UA\":\"Біляші вагові 100г\"}",
          "orders": 143,
          "items": 44,
          "affected_orders": 85,
          "qty": 186.4,
          "repl": 6.8,
          "weight": 6.8,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "142917",
          "name": "{\"uk-UA\":\"Філе куряче охолоджене 500г\"}",
          "orders": 800,
          "items": 598,
          "affected_orders": 82,
          "qty": 11.5,
          "repl": 4.8,
          "weight": 2.2,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "152077",
          "name": "{\"uk-UA\":\"Салат Олів'є з ковбасою ваговий 100г\"}",
          "orders": 394,
          "items": 290,
          "affected_orders": 81,
          "qty": 24.8,
          "repl": 10.3,
          "weight": 3.1,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "2649124",
          "name": "{\"uk-UA\":\"Лимон Інтердонато ваговий 300г\"}",
          "orders": 577,
          "items": 514,
          "affected_orders": 79,
          "qty": 2.1,
          "repl": 0.8,
          "weight": 13.2,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "136434",
          "name": "{\"uk-UA\":\"Салат з крабовими паличками та огірком ваговий 100г\"}",
          "orders": 347,
          "items": 245,
          "affected_orders": 78,
          "qty": 29.4,
          "repl": 15.1,
          "weight": 2.4,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "2629336",
          "name": "{\"uk-UA\":\"Картопля молода мита 500г\"}",
          "orders": 834,
          "items": 662,
          "affected_orders": 78,
          "qty": 9.4,
          "repl": 1.8,
          "weight": 2.4,
          "price": 0
        },
        {
          "category": "Grocery Food",
          "sku": "2607223",
          "name": "{\"uk-UA\":\"Томат ваговий 500г\"}",
          "orders": 710,
          "items": 538,
          "affected_orders": 73,
          "qty": 10.4,
          "repl": 2.2,
          "weight": 3.2,
          "price": 0
        },
        {
          "category": "Cola",
          "sku": "127455",
          "name": "{\"uk-UA\":\"Напій Coca-Cola сильногазований 1,25 л\"}",
          "orders": 501,
          "items": 392,
          "affected_orders": 72,
          "qty": 18.4,
          "repl": 29.8,
          "weight": 0,
          "price": 0
        },
        {
          "category": "Various, mixed",
          "sku": "2630871",
          "name": "{\"uk-UA\":\"Локшина Удон з куркою та соусом теріякі, вагова 100г\"}",
          "orders": 289,
          "items": 192,
          "affected_orders": 72,
          "qty": 35.4,
          "repl": 6.8,
          "weight": 2.1,
          "price": 0
        }
      ]
    }
  },
  "countries": [
    {
      "rank": 1,
      "code": "ro",
      "name_ua": "Румунія",
      "name_en": "Romania",
      "orders": 248302,
      "odr": 37.4,
      "qty": 20.2,
      "wt": 2.5,
      "price": 16.3,
      "repl": 8.7,
      "top5": 40.1,
      "top5x": 50.0,
      "partners": [
        [
          "CARREFOUR",
          67452,
          60.0,
          0
        ],
        [
          "BOLT MARKET (1P)",
          67345,
          0.3,
          0
        ],
        [
          "KAUFLAND",
          52057,
          64.4,
          33.8
        ],
        [
          "REWE",
          34656,
          29.3,
          4.9
        ],
        [
          "AUCHAN",
          18276,
          46.4,
          11.9
        ]
      ]
    },
    {
      "rank": 2,
      "code": "ee",
      "name_ua": "Естонія",
      "name_en": "Estonia",
      "orders": 183332,
      "odr": 13.3,
      "qty": 13.1,
      "wt": 0.3,
      "price": 0,
      "repl": 4.6,
      "top5": 13.9,
      "top5x": 17.1,
      "partners": [
        [
          "BOLT MARKET (1P)",
          75584,
          0.8,
          0.3
        ],
        [
          "RIMI",
          34879,
          29.8,
          8.1
        ],
        [
          "SELVER",
          34120,
          38.8,
          15.9
        ],
        [
          "ARAXES",
          24808,
          0,
          0
        ],
        [
          "ALDAR EESTI",
          3365,
          0,
          0
        ]
      ]
    },
    {
      "rank": 3,
      "code": "lt",
      "name_ua": "Литва",
      "name_en": "Lithuania",
      "orders": 146229,
      "odr": 25.0,
      "qty": 24.1,
      "wt": 2.0,
      "price": 0,
      "repl": 15.6,
      "top5": 20.4,
      "top5x": 25.4,
      "partners": [
        [
          "RIMI",
          39691,
          41.3,
          23.8
        ],
        [
          "REWE",
          38282,
          45.3,
          33.4
        ],
        [
          "BOLT MARKET (1P)",
          38197,
          0.2,
          0
        ],
        [
          "GELSVA",
          13846,
          15.0,
          2.7
        ],
        [
          "UAB ALYNAS",
          4328,
          0,
          0
        ]
      ]
    },
    {
      "rank": 4,
      "code": "ua",
      "name_ua": "Україна",
      "name_en": "Ukraine",
      "orders": 117212,
      "odr": 19.1,
      "qty": 18.2,
      "wt": 2.1,
      "price": 0,
      "repl": 21.0,
      "top5": 19.6,
      "top5x": 19.6,
      "partners": [
        [
          "VARUS",
          31124,
          54.7,
          70.7
        ],
        [
          "LOKO",
          13583,
          6.5,
          0
        ],
        [
          "HOP HEY",
          10108,
          5.1,
          3.8
        ],
        [
          "BEER MARKET",
          7093,
          0,
          0
        ],
        [
          "KOPIYKA",
          6887,
          31.6,
          22.3
        ]
      ]
    }
  ],
  "findings": {
    "ua": [
      {
        "h": "1. Минулий тиждень трохи кращий, але рівень лишається високим",
        "p": "ODR ринку зріс з <b>13.7%</b> (15 черв) до <b>21.0%</b> (31 серп) — це +7.3 п.п. за 12 тижнів. Минулий тиждень: 21.0% проти 21.9% тижнем раніше, обсяг 10.9k замовлень (було 10.8k)."
      },
      {
        "h": "2. Проблема = grocery, а не Stores у цілому",
        "p": "<b>VARUS</b> тримає ODR <b>54.7%</b> (ост. тиждень 63.8%) і сам по собі визначає ринковий рівень. <b>KOPIYKA</b> 25.3% (-16.0 п.п.), <b>SANTIM</b> 29.3% (-8.8 п.п.), <b>KOPIYKA MINI</b> 11.1% (-7.8 п.п.). Алкогольні мережі в ТОП-15 лишаються на <b>0%</b>."
      },
      {
        "h": "3. Є партнери з реальним прогресом — їх процеси треба тиражувати",
        "p": "<b>TAISTRA</b> -5.6 п.п. (ост. 17.3%), <b>RUKAVYCHKA</b> +7.3 п.п. (ост. 29.7%). ODR керований на рівні партнера без змін у продукті."
      },
      {
        "h": "4. Стрибок price defect 10 серпня виглядає як артефакт, не клієнтський біль",
        "p": "На тижні 10 серп price-дефектів було 3721 шт., минулого тижня — 436 шт. Quantity лишається головним драйвером (65.0% усіх item defects). Пакети та OOS на напоях треба чистити окремо від KPI."
      }
    ],
    "en": [
      {
        "h": "1. Last week improved slightly, but the level stays high",
        "p": "Market ODR grew from <b>13.7%</b> (15 Jun) to <b>21.0%</b> (31 Aug) — +7.3 pp over 12 weeks. Last week: 21.0% vs 21.9% the week before, on 10.9k orders (previously 10.8k)."
      },
      {
        "h": "2. The problem is grocery, not Stores as a whole",
        "p": "<b>VARUS</b> holds ODR at <b>54.7%</b> (latest week 63.8%) and sets the market level. <b>KOPIYKA</b> 25.3% (-16.0 pp), <b>SANTIM</b> 29.3% (-8.8 pp), <b>KOPIYKA MINI</b> 11.1% (-7.8 pp). Alcohol chains in the top-15 stay at <b>0%</b>."
      },
      {
        "h": "3. Some partners genuinely improved — their processes should be replicated",
        "p": "<b>TAISTRA</b> -5.6 pp (latest 17.3%), <b>RUKAVYCHKA</b> +7.3 pp (latest 29.7%). ODR is manageable at partner level without product changes."
      },
      {
        "h": "4. The 10 Aug price-defect spike looks like an accounting artefact",
        "p": "Price defects peaked at 3721 items in the week of 10 Aug and were 436 last week. Quantity remains the main driver (65.0% of item defects). Bags and beverage OOS should be cleaned up separately from the KPI."
      }
    ]
  },
  "zero_odr": 7,
  "mwb": {
    "odr_avg": 8.7,
    "odr_last": 9.8,
    "odr_first": 6.9,
    "d": 2.9,
    "repl": 0.6,
    "orders": 15495,
    "orders_last": 1379,
    "weekly": [
      6.9,
      8.9,
      9.7,
      9.4,
      10.3,
      8.0,
      8.9,
      9.7,
      8.6,
      7.0,
      7.0,
      9.8
    ],
    "loko_avg": 6.5,
    "loko_last": 6.9,
    "ruk_avg": 24.8,
    "ruk_last": 29.7
  }
};
